// export default [
//   {
//     id: 72,
//     url: 'string',
//     sort: 0,
//     icon: 'string',
//     keepAlive: 0,
//     parent: 0,
//     name: 'string',
//   },
//   {
//     id: 1,
//     url: 'system',
//     sort: 1,
//     icon: 'icon-yanzhengma',
//     keepAlive: 0,
//     parent: -1,
//     name: '系统管理',
//   },
//   {
//     id: 3,
//     url: 'system/role',
//     sort: 1,
//     icon: 'icon-zhuzhuangtu',
//     keepAlive: 1,
//     parent: 1,
//     name: '角色管理',
//   },
//   {
//     id: 87,
//     url: 'sss',
//     sort: 1,
//     icon: 'icon-fuzhi',
//     keepAlive: 1,
//     parent: -1,
//     name: 'MAERSK',
//   },
//   {
//     id: 111,
//     url: 'gg',
//     sort: 1,
//     icon: 'icon-yun',
//     keepAlive: 1,
//     parent: 87,
//     name: 'gg',
//   },
//   {
//     id: 112,
//     url: 'permisson',
//     sort: 1,
//     icon: 'icon-quanxian',
//     keepAlive: 1,
//     parent: 1,
//     name: '权限管理',
//   },
//   {
//     id: 2,
//     url: 'system/account',
//     sort: 3,
//     icon: 'icon-yun',
//     keepAlive: 0,
//     parent: 1,
//     name: '账号管理',
//   },
//   {
//     id: 5,
//     url: 'system/dict',
//     sort: 4,
//     icon: 'icon-BUG',
//     keepAlive: 1,
//     parent: 1,
//     name: '字典管理',
//   },
//   {
//     id: 4,
//     url: 'system/access',
//     sort: 6,
//     icon: 'icon-shuazi-1',
//     keepAlive: 0,
//     parentId: 1,
//     name: '资源管理',
//   },
// ]
